### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by peter-mach** [Lerg/smartpixel-config-lua#1]
When I choose 'Landscape' mode in the build settings your sample project doesn't tell it's pixel perfect anymore. What is the solution?

**Comment by AvinZarlez** [comment]
Did you change the local contentW, contentH = 320, 480 ? That says the minimal size of your project, and if you don't change it, it will be a portrait within a landscape.

**Comment by peter-mach** [comment]
Yes setting `local contentW, contentH = 480, 320` in config.lua solved the problem. Thanks @TobiahZ
